#!/usr/bin/env python3
"""Generate textbook unit JSON files for Math (人教版), English (PEP), Chinese (部编版)."""
import json
import os

OUTPUT_DIR = os.path.join(os.path.dirname(__file__), 'data')

def unit(uid, name, lessons, kps, desc=""):
    return {"unitId": uid, "unitName": name, "lessons": lessons,
            "knowledgePoints": kps, "description": desc}

def semester(sem_name, units):
    return {"semester": sem_name, "units": units}

def grade(g, name, sems):
    return {"grade": g, "gradeName": name, "semesters": sems}

# ============================================================
# MATH - 人教版
# ============================================================
math_grades = [
    grade(1, "一年级", [
        semester("上册", [
            unit("math-g1-s1-u1", "准备课", ["数一数", "比多少"],
                 ["leaf-001", "leaf-050"], "入学准备，数数和比较"),
            unit("math-g1-s1-u2", "位置", ["上、下、前、后", "左、右"],
                 ["leaf-047"], "基本方位认识"),
            unit("math-g1-s1-u3", "1~5的认识和加减法", ["1~5的认识", "比大小", "第几", "加法", "减法", "0的认识"],
                 ["leaf-001", "leaf-010"], "5以内数的认识和加减法"),
            unit("math-g1-s1-u4", "认识图形（一）", ["立体图形认识"],
                 ["leaf-036"], "长方体、正方体、圆柱、球"),
            unit("math-g1-s1-u5", "6~10的认识和加减法", ["6和7", "8和9", "10", "连加连减", "加减混合"],
                 ["leaf-001", "leaf-010"], "10以内数的认识和加减法"),
            unit("math-g1-s1-u6", "11~20各数的认识", ["数数", "读数", "写数", "10加几和相应减法"],
                 ["leaf-001"], "20以内数的认识"),
            unit("math-g1-s1-u7", "认识钟表", ["认识整时", "认识半时"],
                 ["leaf-019"], "钟表和时间的初步认识"),
            unit("math-g1-s1-u8", "20以内的进位加法", ["9加几", "8/7/6加几", "5/4/3/2加几"],
                 ["leaf-010"], "进位加法"),
        ]),
        semester("下册", [
            unit("math-g1-s2-u1", "认识图形（二）", ["平面图形认识", "图形拼组"],
                 ["leaf-030"], "长方形、正方形、三角形、圆"),
            unit("math-g1-s2-u2", "20以内的退位减法", ["十几减9", "十几减几", "解决问题"],
                 ["leaf-010"], "退位减法"),
            unit("math-g1-s2-u3", "分类与整理", ["分类", "整理"],
                 ["leaf-050"], "按不同标准分类"),
            unit("math-g1-s2-u4", "100以内数的认识", ["数数", "读数写数", "数的顺序", "比较大小", "整十数加一位数"],
                 ["leaf-001"], "100以内数的认识"),
            unit("math-g1-s2-u5", "认识人民币", ["认识人民币", "简单的计算"],
                 ["leaf-018"], "元角分的认识"),
            unit("math-g1-s2-u6", "100以内的加法和减法（一）", ["整十数加减", "两位数加一位数和整十数", "两位数减一位数和整十数"],
                 ["leaf-010"], "100以内加减法"),
            unit("math-g1-s2-u7", "找规律", ["图形规律", "数字规律"],
                 ["leaf-028", "leaf-029"], "简单规律发现"),
        ]),
    ]),
    grade(2, "二年级", [
        semester("上册", [
            unit("math-g2-s1-u1", "长度单位", ["厘米和米", "线段"],
                 ["leaf-020"], "长度单位的认识"),
            unit("math-g2-s1-u2", "100以内的加法和减法（二）", ["不进位加", "进位加", "不退位减", "退位减", "连加连减加减混合"],
                 ["leaf-010"], "竖式加减法"),
            unit("math-g2-s1-u3", "角的初步认识", ["角的认识", "直角"],
                 ["leaf-031"], "角的初步认识"),
            unit("math-g2-s1-u4", "表内乘法（一）", ["乘法初步认识", "2~6的乘法口诀"],
                 ["leaf-011"], "乘法概念和口诀"),
            unit("math-g2-s1-u5", "观察物体（一）", ["从不同方向看"],
                 ["leaf-036"], "空间观察"),
            unit("math-g2-s1-u6", "表内乘法（二）", ["7~9的乘法口诀"],
                 ["leaf-011"], "完整乘法口诀"),
            unit("math-g2-s1-u7", "认识时间", ["分", "时间计算"],
                 ["leaf-019"], "时分的认识"),
            unit("math-g2-s1-u8", "数学广角—搭配（一）", ["简单排列", "简单组合"],
                 ["leaf-072"], "搭配问题入门"),
        ]),
        semester("下册", [
            unit("math-g2-s2-u1", "数据收集整理", ["数据收集", "数据整理"],
                 ["leaf-050", "leaf-051"], "简单统计"),
            unit("math-g2-s2-u2", "表内除法（一）", ["除法初步认识", "2~6的乘法口诀求商"],
                 ["leaf-011"], "除法概念"),
            unit("math-g2-s2-u3", "图形的运动（一）", ["轴对称", "平移", "旋转"],
                 ["leaf-044", "leaf-045"], "图形运动初步"),
            unit("math-g2-s2-u4", "表内除法（二）", ["7~9的乘法口诀求商", "解决问题"],
                 ["leaf-011"], "表内除法完成"),
            unit("math-g2-s2-u5", "混合运算", ["运算顺序", "解决问题"],
                 ["leaf-012"], "四则混合运算入门"),
            unit("math-g2-s2-u6", "有余数的除法", ["余数", "竖式计算", "解决问题"],
                 ["leaf-011"], "有余数除法"),
            unit("math-g2-s2-u7", "万以内数的认识", ["1000以内", "10000以内", "近似数", "整百整千加减"],
                 ["leaf-001", "leaf-002"], "大数认识"),
            unit("math-g2-s2-u8", "克和千克", ["质量单位认识"],
                 ["leaf-021"], "质量单位"),
            unit("math-g2-s2-u9", "数学广角—推理", ["简单推理"],
                 ["leaf-060"], "逻辑推理入门"),
        ]),
    ]),
    grade(3, "三年级", [
        semester("上册", [
            unit("math-g3-s1-u1", "时、分、秒", ["秒的认识", "时间计算"],
                 ["leaf-019"], "时间单位"),
            unit("math-g3-s1-u2", "万以内的加法和减法（一）", ["两位数加减", "几百几十加减", "估算"],
                 ["leaf-010", "leaf-017"], "万以内加减法"),
            unit("math-g3-s1-u3", "测量", ["毫米分分米", "千米", "吨"],
                 ["leaf-020", "leaf-021"], "长度和质量单位"),
            unit("math-g3-s1-u4", "万以内的加法和减法（二）", ["三位数加法", "三位数减法", "加减验算"],
                 ["leaf-010"], "三位数加减法"),
            unit("math-g3-s1-u5", "倍的认识", ["倍的概念", "倍的应用"],
                 ["leaf-065"], "倍数关系"),
            unit("math-g3-s1-u6", "多位数乘一位数", ["口算乘法", "笔算乘法", "解决问题"],
                 ["leaf-011"], "乘法竖式"),
            unit("math-g3-s1-u7", "长方形和正方形", ["四边形", "周长"],
                 ["leaf-034", "leaf-037"], "周长计算"),
            unit("math-g3-s1-u8", "分数的初步认识", ["几分之一", "几分之几", "简单加减"],
                 ["leaf-003"], "分数初步认识"),
            unit("math-g3-s1-u9", "数学广角—集合", ["集合思想"],
                 ["leaf-073"], "集合问题"),
        ]),
        semester("下册", [
            unit("math-g3-s2-u1", "位置与方向（一）", ["东南西北", "路线图"],
                 ["leaf-047"], "方向认识"),
            unit("math-g3-s2-u2", "除数是一位数的除法", ["口算除法", "笔算除法", "估算", "解决问题"],
                 ["leaf-011", "leaf-017"], "除法竖式"),
            unit("math-g3-s2-u3", "复式统计表", ["复式统计表"],
                 ["leaf-051"], "统计表"),
            unit("math-g3-s2-u4", "两位数乘两位数", ["口算乘法", "笔算乘法", "解决问题"],
                 ["leaf-011"], "两位数乘法"),
            unit("math-g3-s2-u5", "面积", ["面积概念", "面积单位", "长方形正方形面积", "面积单位换算"],
                 ["leaf-022", "leaf-039"], "面积计算"),
            unit("math-g3-s2-u6", "年、月、日", ["年月日", "24时计时法"],
                 ["leaf-019"], "时间单位进阶"),
            unit("math-g3-s2-u7", "小数的初步认识", ["小数读写", "小数比较", "小数加减"],
                 ["leaf-005"], "小数初步认识"),
            unit("math-g3-s2-u8", "数学广角—搭配（二）", ["排列组合"],
                 ["leaf-072"], "搭配进阶"),
        ]),
    ]),
    grade(4, "四年级", [
        semester("上册", [
            unit("math-g4-s1-u1", "大数的认识", ["亿以内数", "亿以上数", "计算工具"],
                 ["leaf-002"], "大数认识"),
            unit("math-g4-s1-u2", "公顷和平方千米", ["面积单位"],
                 ["leaf-022"], "大面积单位"),
            unit("math-g4-s1-u3", "角的度量", ["线段直线射线", "角的度量", "角的分类", "画角"],
                 ["leaf-031"], "角的度量"),
            unit("math-g4-s1-u4", "三位数乘两位数", ["口算乘法", "笔算乘法", "积的变化规律", "估算"],
                 ["leaf-011", "leaf-017"], "乘法进阶"),
            unit("math-g4-s1-u5", "平行四边形和梯形", ["垂直与平行", "平行四边形", "梯形"],
                 ["leaf-032", "leaf-034"], "四边形"),
            unit("math-g4-s1-u6", "除数是两位数的除法", ["口算除法", "笔算除法", "商的变化规律"],
                 ["leaf-011"], "两位数除法"),
            unit("math-g4-s1-u7", "条形统计图", ["条形统计图"],
                 ["leaf-052"], "统计图"),
            unit("math-g4-s1-u8", "数学广角—优化", ["沏茶问题", "烙饼问题", "排队问题"],
                 ["leaf-074"], "优化问题"),
        ]),
        semester("下册", [
            unit("math-g4-s2-u1", "四则运算", ["加减法关系", "乘除法关系", "运算顺序", "括号"],
                 ["leaf-012"], "四则运算"),
            unit("math-g4-s2-u2", "观察物体（二）", ["从不同方向看"],
                 ["leaf-036"], "空间观察"),
            unit("math-g4-s2-u3", "运算定律", ["加法运算定律", "乘法运算定律", "简便计算"],
                 ["leaf-012", "leaf-017"], "运算定律"),
            unit("math-g4-s2-u4", "小数的意义和性质", ["小数意义", "小数性质", "小数大小比较", "小数点移动", "近似数"],
                 ["leaf-005"], "小数性质"),
            unit("math-g4-s2-u5", "三角形", ["三角形的特性", "三角形分类", "三角形内角和"],
                 ["leaf-033"], "三角形"),
            unit("math-g4-s2-u6", "小数的加法和减法", ["小数加减法", "小数加减混合"],
                 ["leaf-013"], "小数加减"),
            unit("math-g4-s2-u7", "图形的运动（二）", ["轴对称", "平移"],
                 ["leaf-044", "leaf-045"], "图形运动"),
            unit("math-g4-s2-u8", "统计", ["平均数", "复式条形统计图"],
                 ["leaf-052", "leaf-055"], "平均数"),
            unit("math-g4-s2-u9", "数学广角—鸡兔同笼", ["鸡兔同笼问题"],
                 ["leaf-068"], "鸡兔同笼"),
        ]),
    ]),
    grade(5, "五年级", [
        semester("上册", [
            unit("math-g5-s1-u1", "小数乘法", ["小数乘整数", "小数乘小数", "积的近似数", "简便计算"],
                 ["leaf-013", "leaf-017"], "小数乘法"),
            unit("math-g5-s1-u2", "位置", ["数对"],
                 ["leaf-048"], "数对确定位置"),
            unit("math-g5-s1-u3", "小数除法", ["小数除以整数", "一个数除以小数", "商的近似数", "循环小数"],
                 ["leaf-013"], "小数除法"),
            unit("math-g5-s1-u4", "可能性", ["事件发生的可能性", "可能性的大小"],
                 ["leaf-057", "leaf-058"], "概率初步"),
            unit("math-g5-s1-u5", "简易方程", ["用字母表示数", "方程的意义", "解方程", "实际问题与方程"],
                 ["leaf-024", "leaf-025", "leaf-026"], "方程"),
            unit("math-g5-s1-u6", "多边形的面积", ["平行四边形面积", "三角形面积", "梯形面积", "组合图形面积"],
                 ["leaf-039", "leaf-040"], "面积计算"),
            unit("math-g5-s1-u7", "数学广角—植树问题", ["植树问题"],
                 ["leaf-069"], "植树问题"),
        ]),
        semester("下册", [
            unit("math-g5-s2-u1", "观察物体（三）", ["从不同方向看"],
                 ["leaf-036"], "空间观察进阶"),
            unit("math-g5-s2-u2", "因数与倍数", ["因数和倍数", "2/3/5的倍数特征", "质数和合数"],
                 ["leaf-008", "leaf-009"], "因数倍数"),
            unit("math-g5-s2-u3", "长方体和正方体", ["长方体正方体认识", "表面积", "体积", "容积"],
                 ["leaf-036", "leaf-042", "leaf-043"], "立体图形"),
            unit("math-g5-s2-u4", "分数的意义和性质", ["分数意义", "真分数假分数", "分数基本性质", "约分", "通分"],
                 ["leaf-004"], "分数性质"),
            unit("math-g5-s2-u5", "图形的运动（三）", ["旋转"],
                 ["leaf-045"], "旋转"),
            unit("math-g5-s2-u6", "分数的加法和减法", ["同分母加减", "异分母加减", "分数加减混合"],
                 ["leaf-014"], "分数加减"),
            unit("math-g5-s2-u7", "折线统计图", ["单式", "复式"],
                 ["leaf-053"], "折线统计图"),
            unit("math-g5-s2-u8", "数学广角—找次品", ["找次品"],
                 ["leaf-075"], "找次品"),
        ]),
    ]),
    grade(6, "六年级", [
        semester("上册", [
            unit("math-g6-s1-u1", "分数乘法", ["分数乘整数", "分数乘分数", "倒数"],
                 ["leaf-015"], "分数乘法"),
            unit("math-g6-s1-u2", "位置与方向（二）", ["方向与距离", "路线图"],
                 ["leaf-047"], "方向位置进阶"),
            unit("math-g6-s1-u3", "分数除法", ["分数除以整数", "一个数除以分数", "比"],
                 ["leaf-015", "leaf-027"], "分数除法"),
            unit("math-g6-s1-u4", "比", ["比的意义和性质", "按比分配"],
                 ["leaf-027"], "比"),
            unit("math-g6-s1-u5", "圆", ["圆的认识", "圆的周长", "圆的面积"],
                 ["leaf-035", "leaf-038", "leaf-041"], "圆"),
            unit("math-g6-s1-u6", "百分数（一）", ["百分数意义", "百分数分数小数互化", "百分数应用"],
                 ["leaf-006", "leaf-016"], "百分数"),
            unit("math-g6-s1-u7", "扇形统计图", ["扇形统计图"],
                 ["leaf-054"], "扇形统计图"),
            unit("math-g6-s1-u8", "数学广角—数与形", ["数形结合"],
                 ["leaf-077"], "数与形"),
        ]),
        semester("下册", [
            unit("math-g6-s2-u1", "负数", ["负数的认识", "数轴"],
                 ["leaf-007"], "负数"),
            unit("math-g6-s2-u2", "百分数（二）", ["折扣", "成数", "税率", "利率"],
                 ["leaf-016"], "百分数应用"),
            unit("math-g6-s2-u3", "圆柱与圆锥", ["圆柱认识", "圆柱表面积", "圆柱体积", "圆锥体积"],
                 ["leaf-036", "leaf-042", "leaf-043"], "圆柱圆锥"),
            unit("math-g6-s2-u4", "比例", ["比例意义", "正比例反比例", "比例尺", "图形放大缩小"],
                 ["leaf-027", "leaf-046", "leaf-049"], "比例"),
            unit("math-g6-s2-u5", "数学广角—鸽巢问题", ["鸽巢原理"],
                 ["leaf-076"], "鸽巢原理"),
            unit("math-g6-s2-u6", "总复习", ["数与代数", "图形与几何", "统计与概率", "综合应用"],
                 ["leaf-012", "leaf-039", "leaf-055", "leaf-062"], "小学总复习"),
        ]),
    ]),
]

math_tree = {"subject": "数学", "textbookType": "人教版", "version": "2024秋", "grades": math_grades}

# ============================================================
# ENGLISH - PEP (人教版) - starts Grade 3
# ============================================================
en_grades = [
    grade(3, "三年级", [
        semester("上册", [
            unit("en-g3-s1-u1", "Unit 1 Hello", ["Hello/Goodbye", "I'm.../My name is..."],
                 ["en-leaf-001", "en-leaf-041"], "问候与自我介绍"),
            unit("en-g3-s1-u2", "Unit 2 Colours", ["颜色词汇", "This is.../Nice to meet you"],
                 ["en-leaf-013", "en-leaf-041"], "颜色和介绍"),
            unit("en-g3-s1-u3", "Unit 3 Look at me", ["身体部位", "How are you?"],
                 ["en-leaf-012", "en-leaf-041"], "身体部位和问候"),
            unit("en-g3-s1-u4", "Unit 4 We love animals", ["动物词汇", "What's this?/It's..."],
                 ["en-leaf-010", "en-leaf-037"], "动物和问答"),
            unit("en-g3-s1-u5", "Unit 5 Let's eat", ["食物词汇", "I like.../Have some..."],
                 ["en-leaf-011", "en-leaf-045"], "食物"),
            unit("en-g3-s1-u6", "Unit 6 Happy birthday", ["数字1-10", "How many?"],
                 ["en-leaf-027", "en-leaf-037"], "数字和生日"),
        ]),
        semester("下册", [
            unit("en-g3-s2-u1", "Unit 1 Welcome back to school", ["国家词汇", "I'm from.../Where are you from?"],
                 ["en-leaf-014", "en-leaf-038"], "国家和来历"),
            unit("en-g3-s2-u2", "Unit 2 My family", ["家庭成员", "Who's that man/woman?"],
                 ["en-leaf-008", "en-leaf-042"], "家庭"),
            unit("en-g3-s2-u3", "Unit 3 At the zoo", ["动物特征", "It's so tall/big/small"],
                 ["en-leaf-010", "en-leaf-021"], "动物描述"),
            unit("en-g3-s2-u4", "Unit 4 Where is my car?", ["方位词", "Where is...?/It's in/on/under..."],
                 ["en-leaf-029", "en-leaf-038"], "方位"),
            unit("en-g3-s2-u5", "Unit 5 Do you like pears?", ["水果词汇", "Do you like...?/Yes,I do/No,I don't"],
                 ["en-leaf-011", "en-leaf-037"], "水果和喜好"),
            unit("en-g3-s2-u6", "Unit 6 How many?", ["数字11-20", "How many...do you have?"],
                 ["en-leaf-027", "en-leaf-038"], "数量"),
        ]),
    ]),
    grade(4, "四年级", [
        semester("上册", [
            unit("en-g4-s1-u1", "Unit 1 My classroom", ["教室物品", "What's in the classroom?"],
                 ["en-leaf-009", "en-leaf-039"], "教室"),
            unit("en-g4-s1-u2", "Unit 2 My schoolbag", ["学习用品", "What's in your schoolbag?"],
                 ["en-leaf-009", "en-leaf-039"], "书包"),
            unit("en-g4-s1-u3", "Unit 3 My friends", ["外貌描述", "He/She is.../His/Her name is..."],
                 ["en-leaf-021", "en-leaf-025"], "朋友"),
            unit("en-g4-s1-u4", "Unit 4 At the farm", ["农场动物和蔬菜", "Are these/those...?"],
                 ["en-leaf-010", "en-leaf-037"], "农场"),
            unit("en-g4-s1-u5", "Unit 5 Dinner's ready", ["餐具和食物", "What would you like?"],
                 ["en-leaf-011", "en-leaf-045"], "用餐"),
            unit("en-g4-s1-u6", "Unit 6 Meet my family", ["家庭成员", "How many people are there?"],
                 ["en-leaf-008", "en-leaf-039"], "家庭"),
        ]),
        semester("下册", [
            unit("en-g4-s2-u1", "Unit 1 My school", ["学校场所", "Where is the...?/It's on the first floor"],
                 ["en-leaf-014", "en-leaf-029"], "学校"),
            unit("en-g4-s2-u2", "Unit 2 What time is it", ["时间表达", "What time is it?/It's...o'clock"],
                 ["en-leaf-027", "en-leaf-038"], "时间"),
            unit("en-g4-s2-u3", "Unit 3 Weather", ["天气词汇", "What's the weather like?"],
                 ["en-leaf-048", "en-leaf-038"], "天气"),
            unit("en-g4-s2-u4", "Unit 4 At the farm", ["农场", "Are these...?/Yes,they are"],
                 ["en-leaf-010", "en-leaf-037"], "农场进阶"),
            unit("en-g4-s2-u5", "Unit 5 My clothes", ["服装词汇", "Whose...are these/those?"],
                 ["en-leaf-013", "en-leaf-025"], "服装"),
            unit("en-g4-s2-u6", "Unit 6 Shopping", ["购物", "Can I help you?/How much is it?"],
                 ["en-leaf-046", "en-leaf-038"], "购物"),
        ]),
    ]),
    grade(5, "五年级", [
        semester("上册", [
            unit("en-g5-s1-u1", "Unit 1 What's he like", ["性格描述词", "What's he like?/He is..."],
                 ["en-leaf-022", "en-leaf-018"], "人物描述"),
            unit("en-g5-s1-u2", "Unit 2 My week", ["星期和课程", "What do you have on...?"],
                 ["en-leaf-024", "en-leaf-043"], "一周安排"),
            unit("en-g5-s1-u3", "Unit 3 What would you like", ["食物饮品", "What would you like to eat/drink?"],
                 ["en-leaf-011", "en-leaf-045"], "饮食偏好"),
            unit("en-g5-s1-u4", "Unit 4 What can you do", ["能力表达", "What can you do?/I can..."],
                 ["en-leaf-016", "en-leaf-017"], "能力"),
            unit("en-g5-s1-u5", "Unit 5 There is a big bed", ["房间物品", "There is/are..."],
                 ["en-leaf-039", "en-leaf-014"], "there be句型"),
            unit("en-g5-s1-u6", "Unit 6 In a nature park", ["自然景观", "Is there...?/Are there...?"],
                 ["en-leaf-039", "en-leaf-037"], "there be疑问句"),
        ]),
        semester("下册", [
            unit("en-g5-s2-u1", "Unit 1 My day", ["日常活动", "When do you...?/I usually...at..."],
                 ["en-leaf-017", "en-leaf-031"], "日常作息"),
            unit("en-g5-s2-u2", "Unit 2 My favourite season", ["季节", "Which season do you like best?"],
                 ["en-leaf-048", "en-leaf-038"], "季节"),
            unit("en-g5-s2-u3", "Unit 3 My school calendar", ["月份和节日", "When is...?/It's in..."],
                 ["en-leaf-028", "en-leaf-050"], "校历"),
            unit("en-g5-s2-u4", "Unit 4 When is the art show", ["序数词和日期", "When is...?/It's on..."],
                 ["en-leaf-027", "en-leaf-038"], "日期表达"),
            unit("en-g5-s2-u5", "Unit 5 Whose dog is it", ["物主代词", "Whose...is this/are these?"],
                 ["en-leaf-025", "en-leaf-038"], "物主代词"),
            unit("en-g5-s2-u6", "Unit 6 Work quietly", ["现在进行时", "What are they doing?/They are..."],
                 ["en-leaf-032", "en-leaf-038"], "现在进行时"),
        ]),
    ]),
    grade(6, "六年级", [
        semester("上册", [
            unit("en-g6-s1-u1", "Unit 1 How can I get there", ["地点方位", "Where is...?/How can I get to...?"],
                 ["en-leaf-014", "en-leaf-047"], "问路指路"),
            unit("en-g6-s1-u2", "Unit 2 Ways to go to school", ["交通方式", "How do you come to school?"],
                 ["en-leaf-016", "en-leaf-038"], "交通"),
            unit("en-g6-s1-u3", "Unit 3 My weekend plan", ["将来时", "What are you going to do?"],
                 ["en-leaf-034", "en-leaf-051"], "将来时"),
            unit("en-g6-s1-u4", "Unit 4 I have a pen pal", ["爱好", "What are his/her hobbies?"],
                 ["en-leaf-044", "en-leaf-031"], "兴趣爱好"),
            unit("en-g6-s1-u5", "Unit 5 What does he do", ["职业", "What does he/she do?/He/She is a..."],
                 ["en-leaf-017", "en-leaf-038"], "职业"),
            unit("en-g6-s1-u6", "Unit 6 How do you feel", ["情绪", "How do you feel?/I feel..."],
                 ["en-leaf-022", "en-leaf-038"], "情绪表达"),
        ]),
        semester("下册", [
            unit("en-g6-s2-u1", "Unit 1 How tall are you", ["比较级最高级", "How tall are you?/I'm...taller than..."],
                 ["en-leaf-023", "en-leaf-038"], "比较级"),
            unit("en-g6-s2-u2", "Unit 2 Last weekend", ["一般过去时", "What did you do last weekend?"],
                 ["en-leaf-033", "en-leaf-038"], "过去时"),
            unit("en-g6-s2-u3", "Unit 3 Where did you go", ["过去时进阶", "Where did you go?/I went to..."],
                 ["en-leaf-033", "en-leaf-047"], "过去时应用"),
            unit("en-g6-s2-u4", "Unit 4 Then and now", ["过去与现在对比", "There was/were.../Now there is/are..."],
                 ["en-leaf-033", "en-leaf-039"], "时态对比"),
        ]),
    ]),
]

en_tree = {"subject": "英语", "textbookType": "PEP人教版", "version": "2024秋", "grades": en_grades}

# ============================================================
# CHINESE - 部编版
# ============================================================
cn_grades = [
    grade(1, "一年级", [
        semester("上册", [
            unit("cn-g1-s1-u1", "识字（一）", ["天地人", "金木水火土", "口耳目", "日月水火", "对韵歌"],
                 ["cn-leaf-007", "cn-leaf-008"], "识字入门"),
            unit("cn-g1-s1-u2", "汉语拼音", ["a o e", "i u ü", "b p m f", "d t n l", "g k h", "j q x", "z c s", "zh ch sh r", "ai ei ui", "ao ou iu", "ie üe er", "an en in un ün", "ang eng ing ong"],
                 ["cn-leaf-001", "cn-leaf-002", "cn-leaf-003", "cn-leaf-004", "cn-leaf-005", "cn-leaf-006"], "拼音系统学习"),
            unit("cn-g1-s1-u3", "课文（一）", ["秋天", "小小的船", "江南", "四季"],
                 ["cn-leaf-030", "cn-leaf-036"], "课文朗读理解"),
            unit("cn-g1-s1-u4", "识字（二）", ["画", "大小多少", "小书包", "日月明"],
                 ["cn-leaf-009", "cn-leaf-010", "cn-leaf-011"], "识字进阶"),
            unit("cn-g1-s1-u5", "课文（二）", ["项链", "雪地里的小画家", "乌鸦喝水", "小蜗牛"],
                 ["cn-leaf-030", "cn-leaf-038"], "课文理解"),
        ]),
        semester("下册", [
            unit("cn-g1-s2-u1", "识字（一）", ["春夏秋冬", "姓氏歌", "小青蛙", "猜字谜"],
                 ["cn-leaf-007", "cn-leaf-009", "cn-leaf-011"], "识字"),
            unit("cn-g1-s2-u2", "课文（一）", ["吃水不忘挖井人", "我多想去看看", "四个太阳"],
                 ["cn-leaf-030", "cn-leaf-031"], "课文理解"),
            unit("cn-g1-s2-u3", "课文（二）", ["静夜思", "夜色", "彩虹", "端午粽"],
                 ["cn-leaf-036", "cn-leaf-046"], "古诗和课文"),
            unit("cn-g1-s2-u4", "识字（二）", ["动物儿歌", "古对今", "操场上", "人之初"],
                 ["cn-leaf-009", "cn-leaf-015", "cn-leaf-046"], "识字"),
            unit("cn-g1-s2-u5", "课文（三）", ["古诗二首", "荷叶圆圆", "要下雨了"],
                 ["cn-leaf-030", "cn-leaf-036"], "课文"),
            unit("cn-g1-s2-u6", "课文（四）", ["文具的家", "一分钟", "动物王国开大会", "小猴子下山"],
                 ["cn-leaf-030", "cn-leaf-051"], "课文"),
            unit("cn-g1-s2-u7", "课文（五）", ["棉花姑娘", "咕咚", "小壁虎借尾巴"],
                 ["cn-leaf-030", "cn-leaf-038"], "课文"),
        ]),
    ]),
    grade(2, "二年级", [
        semester("上册", [
            unit("cn-g2-s1-u1", "识字", ["小蝌蚪找妈妈", "我是什么", "植物妈妈有办法", "场景歌", "树之歌", "拍手歌", "田家四季歌"],
                 ["cn-leaf-009", "cn-leaf-015", "cn-leaf-016"], "识字单元"),
            unit("cn-g2-s1-u2", "课文（一）", ["曹冲称象", "玲玲的画", "一封信", "妈妈睡了"],
                 ["cn-leaf-030", "cn-leaf-031"], "课文理解"),
            unit("cn-g2-s1-u3", "课文（二）", ["古诗二首", "黄山奇石", "日月潭", "葡萄沟"],
                 ["cn-leaf-036", "cn-leaf-042"], "写景课文"),
            unit("cn-g2-s1-u4", "课文（三）", ["坐井观天", "寒号鸟", "我要的是葫芦"],
                 ["cn-leaf-027", "cn-leaf-030"], "寓言故事"),
            unit("cn-g2-s1-u5", "课文（四）", ["大禹治水", "朱德的扁担", "难忘的泼水节"],
                 ["cn-leaf-030", "cn-leaf-031"], "人物故事"),
            unit("cn-g2-s1-u6", "课文（五）", ["古诗二首", "雾在哪里", "雪孩子", "狐假虎威"],
                 ["cn-leaf-036", "cn-leaf-027"], "古诗寓言"),
        ]),
        semester("下册", [
            unit("cn-g2-s2-u1", "课文（一）", ["古诗二首", "找春天", "开满鲜花的小路", "邓小平爷爷植树"],
                 ["cn-leaf-036", "cn-leaf-042"], "春天主题"),
            unit("cn-g2-s2-u2", "课文（二）", ["雷锋叔叔你在哪里", "千人糕", "一匹出色的马"],
                 ["cn-leaf-030", "cn-leaf-031"], "人物品德"),
            unit("cn-g2-s2-u3", "识字", ["神州谣", "传统节日", "贝的故事", "中国美食"],
                 ["cn-leaf-009", "cn-leaf-015"], "文化识字"),
            unit("cn-g2-s2-u4", "课文（三）", ["彩色的梦", "枫树上的喜鹊", "沙滩上的童话", "我是一只小虫子"],
                 ["cn-leaf-027", "cn-leaf-043"], "想象课文"),
            unit("cn-g2-s2-u5", "课文（四）", ["寓言二则", "画杨桃", "小马过河"],
                 ["cn-leaf-027", "cn-leaf-030"], "寓言哲理"),
            unit("cn-g2-s2-u6", "课文（五）", ["古诗二首", "雷雨", "要是你在野外迷了路", "太空生活趣事多"],
                 ["cn-leaf-036", "cn-leaf-035"], "自然科普"),
            unit("cn-g2-s2-u7", "课文（六）", ["大象的耳朵", "蜘蛛开店", "青蛙卖泥塘", "小毛虫"],
                 ["cn-leaf-027", "cn-leaf-030"], "童话故事"),
        ]),
    ]),
    grade(3, "三年级", [
        semester("上册", [
            unit("cn-g3-s1-u1", "课文（一）", ["大青树下的小学", "花的学校", "不懂就要问"],
                 ["cn-leaf-030", "cn-leaf-031"], "学校生活"),
            unit("cn-g3-s1-u2", "课文（二）", ["古诗三首", "铺满金色巴掌的水泥道", "秋天的雨", "听听秋的声音"],
                 ["cn-leaf-036", "cn-leaf-042", "cn-leaf-047"], "秋天主题"),
            unit("cn-g3-s1-u3", "课文（三）", ["去年的树", "在牛肚子里旅行", "一块奶酪"],
                 ["cn-leaf-027", "cn-leaf-033"], "童话"),
            unit("cn-g3-s1-u4", "课文（四）", ["总也倒不了的老屋", "胡萝卜先生的长胡子", "不会叫的狗"],
                 ["cn-leaf-033", "cn-leaf-043"], "预测阅读"),
            unit("cn-g3-s1-u5", "习作+课文", ["搭船的鸟", "金色的草地", "习作:我们眼中的缤纷世界"],
                 ["cn-leaf-039", "cn-leaf-042"], "观察写作"),
            unit("cn-g3-s1-u6", "课文（五）", ["古诗三首", "富饶的西沙群岛", "海滨小城", "美丽的小兴安岭"],
                 ["cn-leaf-036", "cn-leaf-034", "cn-leaf-042"], "祖国山河"),
            unit("cn-g3-s1-u7", "课文（六）", ["大自然的声音", "读不完的大书", "父亲树林和鸟"],
                 ["cn-leaf-034", "cn-leaf-042"], "自然"),
            unit("cn-g3-s1-u8", "课文（七）", ["司马光", "掌声", "灰雀", "手术台就是阵地"],
                 ["cn-leaf-030", "cn-leaf-041"], "人物品质"),
        ]),
        semester("下册", [
            unit("cn-g3-s2-u1", "课文（一）", ["绝句", "惠崇春江晚景", "三衢道中", "燕子", "荷花", "昆虫备忘录"],
                 ["cn-leaf-036", "cn-leaf-042", "cn-leaf-047"], "春天"),
            unit("cn-g3-s2-u2", "课文（二）", ["守株待兔", "陶罐和铁罐", "鹿角和鹿腿", "池子与河流"],
                 ["cn-leaf-027", "cn-leaf-028", "cn-leaf-033"], "寓言"),
            unit("cn-g3-s2-u3", "课文（三）", ["元日", "清明", "九月九日忆山东兄弟", "纸的发明", "赵州桥", "一幅名扬中外的画"],
                 ["cn-leaf-036", "cn-leaf-034"], "传统文化"),
            unit("cn-g3-s2-u4", "课文（四）", ["花钟", "蜜蜂", "小虾"],
                 ["cn-leaf-034", "cn-leaf-039"], "观察发现"),
            unit("cn-g3-s2-u5", "课文（五）", ["小真的长头发", "我变成了一棵树"],
                 ["cn-leaf-043", "cn-leaf-039"], "想象"),
            unit("cn-g3-s2-u6", "课文（六）", ["童年的水墨画", "一只窝囊的大老虎", "我们家的男子汉", "我不能失信"],
                 ["cn-leaf-033", "cn-leaf-041"], "童年"),
            unit("cn-g3-s2-u7", "课文（七）", ["海底世界", "火烧云"],
                 ["cn-leaf-034", "cn-leaf-042"], "奇妙世界"),
            unit("cn-g3-s2-u8", "课文（八）", ["慢性子裁缝和急性子顾客", "方帽子店", "漏", "枣核"],
                 ["cn-leaf-033", "cn-leaf-027"], "故事"),
        ]),
    ]),
    grade(4, "四年级", [
        semester("上册", [
            unit("cn-g4-s1-u1", "课文（一）", ["观潮", "走月亮", "现代诗二首", "繁星"],
                 ["cn-leaf-034", "cn-leaf-042", "cn-leaf-027"], "自然之美"),
            unit("cn-g4-s1-u2", "课文（二）", ["一个豆荚里的五粒豆", "蝙蝠和雷达", "呼风唤雨的世纪"],
                 ["cn-leaf-034", "cn-leaf-035"], "科普"),
            unit("cn-g4-s1-u3", "课文（三）", ["古诗三首", "爬山虎的脚", "蟋蟀的住宅"],
                 ["cn-leaf-036", "cn-leaf-034", "cn-leaf-039"], "观察"),
            unit("cn-g4-s1-u4", "课文（四）", ["盘古开天地", "精卫填海", "普罗米修斯", "女娲补天"],
                 ["cn-leaf-033", "cn-leaf-043"], "神话"),
            unit("cn-g4-s1-u5", "课文（五）", ["麻雀", "爬天都峰", "习作:生活万花筒"],
                 ["cn-leaf-041", "cn-leaf-039"], "写事"),
            unit("cn-g4-s1-u6", "课文（六）", ["古诗三首", "为中华之崛起而读书", "梅兰芳蓄须", "延安我把你追寻"],
                 ["cn-leaf-036", "cn-leaf-041"], "家国情怀"),
            unit("cn-g4-s1-u7", "课文（七）", ["王戎不取道旁李", "西门豹治邺", "故事二则"],
                 ["cn-leaf-037", "cn-leaf-028"], "历史故事"),
        ]),
        semester("下册", [
            unit("cn-g4-s2-u1", "课文（一）", ["四时田园杂兴", "宿新市徐公店", "清平乐村居", "乡下人家", "天窗", "三月桃花水"],
                 ["cn-leaf-036", "cn-leaf-042"], "乡村"),
            unit("cn-g4-s2-u2", "课文（二）", ["琥珀", "飞向蓝天的恐龙", "纳米技术就在我们身边", "千年梦圆在今朝"],
                 ["cn-leaf-034", "cn-leaf-035"], "科技"),
            unit("cn-g4-s2-u3", "课文（三）", ["短诗三首", "绿", "白桦", "在天晴了的时候"],
                 ["cn-leaf-027", "cn-leaf-043"], "现代诗"),
            unit("cn-g4-s2-u4", "课文（四）", ["猫", "母鸡", "白鹅"],
                 ["cn-leaf-042", "cn-leaf-031"], "动物"),
            unit("cn-g4-s2-u5", "课文（五）", ["海上日出", "记金华的双龙洞", "颐和园", "七月的天山"],
                 ["cn-leaf-041", "cn-leaf-042"], "游记"),
            unit("cn-g4-s2-u6", "课文（六）", ["小英雄雨来", "我们家的男子汉", "芦花鞋"],
                 ["cn-leaf-033", "cn-leaf-041"], "长文章"),
            unit("cn-g4-s2-u7", "课文（七）", ["古诗三首", "黄继光", "挑山工", "我的自画像"],
                 ["cn-leaf-036", "cn-leaf-041"], "人物"),
            unit("cn-g4-s2-u8", "课文（八）", ["宝葫芦的秘密", "巨人的花园", "海的女儿"],
                 ["cn-leaf-033", "cn-leaf-043"], "童话"),
        ]),
    ]),
    grade(5, "五年级", [
        semester("上册", [
            unit("cn-g5-s1-u1", "课文（一）", ["白鹭", "落花生", "桂花雨", "珍珠鸟"],
                 ["cn-leaf-031", "cn-leaf-032", "cn-leaf-042"], "借物抒情"),
            unit("cn-g5-s1-u2", "课文（二）", ["搭石", "将相和", "什么比猎豹的速度更快", "冀中的地道战"],
                 ["cn-leaf-033", "cn-leaf-035"], "提高阅读速度"),
            unit("cn-g5-s1-u3", "课文（三）", ["猎人海力布", "牛郎织女（一）", "牛郎织女（二）"],
                 ["cn-leaf-033", "cn-leaf-043"], "民间故事"),
            unit("cn-g5-s1-u4", "课文（四）", ["古诗三首", "少年中国说", "圆明园的毁灭", "木笛"],
                 ["cn-leaf-036", "cn-leaf-041"], "爱国"),
            unit("cn-g5-s1-u5", "课文（五）", ["太阳", "松鼠", "习作:介绍一种事物"],
                 ["cn-leaf-034", "cn-leaf-039"], "说明文"),
            unit("cn-g5-s1-u6", "课文（六）", ["慈母情深", "父爱之舟", '"精彩极了"和"糟糕透了"'],
                 ["cn-leaf-041", "cn-leaf-031"], "父母之爱"),
            unit("cn-g5-s1-u7", "课文（七）", ["古诗词三首", "四季之美", "鸟的天堂", "月迹"],
                 ["cn-leaf-036", "cn-leaf-042", "cn-leaf-047"], "景致"),
            unit('cn-g5-s1-u8', '课文（八）', ['古人谈读书', '忆读书', '我的"长生果"'],
                 ["cn-leaf-037", "cn-leaf-031"], "读书"),
        ]),
        semester("下册", [
            unit("cn-g5-s2-u1", "课文（一）", ["古诗三首", "祖父的园子", "月是故乡明", "梅花魂"],
                 ["cn-leaf-036", "cn-leaf-042"], "童年往事"),
            unit("cn-g5-s2-u2", "课文（二）", ["草船借箭", "景阳冈", "猴王出世", "红楼春趣"],
                 ["cn-leaf-033", "cn-leaf-031"], "古典名著"),
            unit("cn-g5-s2-u3", "课文（三）", ["古诗三首", "青山处处埋忠骨", "军神", "清贫", "方志敏"],
                 ["cn-leaf-036", "cn-leaf-041"], "家国"),
            unit("cn-g5-s2-u4", "课文（四）", ["人物描写一组", "刷子李"],
                 ["cn-leaf-041", "cn-leaf-032"], "人物描写"),
            unit("cn-g5-s2-u5", "课文（五）", ["威尼斯的小艇", "牧场之国", "金字塔"],
                 ["cn-leaf-042", "cn-leaf-034"], "异域风情"),
            unit("cn-g5-s2-u6", "课文（六）", ["文言文二则", "真理诞生于一百个问号之后", "表里的生物"],
                 ["cn-leaf-037", "cn-leaf-034"], "科学精神"),
            unit("cn-g5-s2-u7", "课文（七）", ["牧场之国", "金字塔"],
                 ["cn-leaf-042", "cn-leaf-035"], "世界风光"),
            unit("cn-g5-s2-u8", "课文（八）", ["杨氏之子", "手指", "童年的发现"],
                 ["cn-leaf-037", "cn-leaf-027"], "幽默风趣"),
        ]),
    ]),
    grade(6, "六年级", [
        semester("上册", [
            unit("cn-g6-s1-u1", "课文（一）", ["草原", "丁香结", "古诗词三首", "花之歌"],
                 ["cn-leaf-036", "cn-leaf-042", "cn-leaf-027"], "自然触摸"),
            unit("cn-g6-s1-u2", "课文（二）", ["七律长征", "狼牙山五壮士", "开国大典", "灯光"],
                 ["cn-leaf-041", "cn-leaf-031"], "革命岁月"),
            unit("cn-g6-s1-u3", "课文（三）", ["竹节人", "宇宙生命之谜", "故宫博物院"],
                 ["cn-leaf-035", "cn-leaf-034", "cn-leaf-033"], "阅读策略"),
            unit("cn-g6-s1-u4", "课文（四）", ["桥", "穷人", "在柏林"],
                 ["cn-leaf-033", "cn-leaf-031", "cn-leaf-041"], "小说"),
            unit("cn-g6-s1-u5", "课文（五）", ["夏天里的成长", "盼", "习作:围绕中心意思写"],
                 ["cn-leaf-041", "cn-leaf-039"], "中心意思"),
            unit("cn-g6-s1-u6", "课文（六）", ["古诗三首", "只有一个地球", "青山不老", "三黑和土地"],
                 ["cn-leaf-036", "cn-leaf-034"], "保护地球"),
            unit("cn-g6-s1-u7", "课文（七）", ["文言文二则", "月光曲", "京剧趣谈"],
                 ["cn-leaf-037", "cn-leaf-042"], "艺术之美"),
            unit("cn-g6-s1-u8", "课文（八）", ["少年闰土", "好的故事", "我的伯父鲁迅先生", "有的人"],
                 ["cn-leaf-033", "cn-leaf-041", "cn-leaf-031"], "鲁迅"),
        ]),
        semester("下册", [
            unit("cn-g6-s2-u1", "课文（一）", ["北京的春节", "腊八粥", "古诗三首", "藏戏"],
                 ["cn-leaf-036", "cn-leaf-042", "cn-leaf-034"], "民风民俗"),
            unit("cn-g6-s2-u2", "课文（二）", ["鲁滨逊漂流记", "骑鹅旅行记", "汤姆索亚历险记"],
                 ["cn-leaf-033", "cn-leaf-043"], "外国名著"),
            unit("cn-g6-s2-u3", "课文（三）", ["匆匆", "那个星期天"],
                 ["cn-leaf-027", "cn-leaf-041"], "真情实感"),
            unit("cn-g6-s2-u4", "课文（四）", ["十六年前的回忆", "为人民服务", "金色的鱼钩"],
                 ["cn-leaf-041", "cn-leaf-031"], "理想信念"),
            unit("cn-g6-s2-u5", "课文（五）", ["文言文二则", "真理诞生于一百个问号之后", "表里的生物"],
                 ["cn-leaf-037", "cn-leaf-034"], "科学精神"),
            unit("cn-g6-s2-u6", "课文（六）", ["回忆往事", "老师领进门", "作文上的红双圈"],
                 ["cn-leaf-041", "cn-leaf-045"], "难忘小学生活"),
        ]),
    ]),
]

cn_tree = {"subject": "语文", "textbookType": "部编版", "version": "2024秋", "grades": cn_grades}

# ============================================================
# Write files
# ============================================================
for name, tree in [("textbook_units_math.json", math_tree),
                   ("textbook_units_english.json", en_tree),
                   ("textbook_units_chinese.json", cn_tree)]:
    path = os.path.join(OUTPUT_DIR, name)
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(tree, f, ensure_ascii=False, indent=2)
    # Count units
    total_units = 0
    for g in tree['grades']:
        for s in g['semesters']:
            total_units += len(s['units'])
    print(f"  {name}: {len(tree['grades'])} grades, {total_units} units")

print("Done!")
